In [4]:
import pandas as pd 
aljazerra_data = pd.read_csv("aljazerra_cleaned_data.csv", sep= ",")

In [5]:
aljazerra_data.head()

,Unnamed: 0,Unnamed: 0.1,date,title,head_titel,main_content,title_positive_scores,title_negative_scores,title_neutral_scores,main_content_positive_scores,main_content_negative_scores,main_content_neutral_scores,title_main_content_positive_mean,title_main_content_negaitve_mean,title_main_content_neutral_mean
0,0,0,Published On 19 Dec 2022,pure joy argentina erupts celebration win,An explosion of hope and joy engulfs the natio...,buenos aires argentina game say sunday truism ...,0.655,0.000,0.345,0.217,0.076,0.707,0.4360,0.076,0.707
1,1,1,Published On 19 Dec 2022,lionel messi breakdown career highlights,After inspiring Argentina to a historic World ...,lionel messi finally forward delighted years s...,0.000,0.000,1.000,0.203,0.047,0.750,0.1015,0.047,0.750
2,2,2,Published On 19 Dec 2022,bisht messi wearing,The emir of Qatar put a bisht on Argentina cap...,trophy presentation argentina win france final...,0.000,0.000,1.000,0.282,0.063,0.655,0.1410,0.063,0.655
3,3,3,Published On 19 Dec 2022,predictions many games ai get right,"In total, Kashef, our AI robot, had a 67 perce...",produced incredible start tournament al jazeer...,0.000,0.000,1.000,0.258,0.065,0.677,0.1290,0.065,0.677
4,4,4,Published On 18 Dec 2022,tears relief joy messi lifts argentina,Waves of euphoria sweep through Lusail Stadium...,lusail leaped air fists pumped delight finally...,0.585,0.161,0.254,0.244,0.092,0.664,0.4145,0.092,0.664

In [6]:
aljazerra_data = aljazerra_data.sort_values('title_main_content_negaitve_mean', ascending=False)
aljazerra_data.head()

NameError: name 'df' is not defined